In [26]:
import pandas as pd
import matplotlib.pyplot as plt


# Chargement du dataset
df = pd.read_csv('./data/dunder_mifflin_sales_realiste.csv')
df.head(20)

,order_id,order_date,year,month,salesperson,client_name,client_segment,client_city,region,product_name,...,quantity,unit_price,discount_pct,discount_amount,gross_revenue,net_revenue,channel,is_returned,return_date,monthly_target
0,DM-010029,2005-01-01,2005,1,Michael Scott,Blue Cross Health,Enterprise,New York,Northeast,Copy Paper - Premium (Case),...,1,57.47,0.15,8.62,57.47,48.85,Direct,False,NaN,114.98
1,DM-001029,2005-01-01,2005,1,Dwight Schrute,Dunmore Correctional,Government,Dunmore,Northeast,Copy Paper - Premium (Case),...,10,52.05,0.00,0.00,520.54,520.54,Phone,False,NaN,252.95
2,DM-001018,2005-01-01,2005,1,Dwight Schrute,Gerber & Associates,Mid-Market,New York,Northeast,Manila Folders (Pack),...,3,9.37,0.00,0.00,28.11,28.11,Email,False,NaN,45.95
3,DM-011929,2005-01-01,2005,1,Stanley Hudson,Prestige Direct,Mid-Market,Scranton,Northeast,Color Copy Paper (Pack),...,12,28.09,0.00,0.00,337.12,337.12,Direct,False,NaN,53.34
4,DM-010013,2005-01-02,2005,1,Michael Scott,Dunmore Correctional,Government,Dunmore,Northeast,Laser Toner - Color,...,1,117.41,0.10,11.74,117.41,105.67,Referral,False,NaN,250.89
5,DM-010022,2005-01-02,2005,1,Michael Scott,Poor Richard's Pub,SMB,Scranton,Northeast,Specialty Paper - Glossy (Pack),...,3,34.47,0.10,10.34,103.42,93.08,Email,False,NaN,73.16
6,DM-010017,2005-01-02,2005,1,Michael Scott,Pioneer Healthcare,Internal,Utica,Northeast,Specialty Paper - Glossy (Pack),...,5,34.37,0.20,34.37,171.85,137.48,Phone,False,NaN,73.16
7,DM-001006,2005-01-02,2005,1,Dwight Schrute,Dunmore Correctional,Government,Dunmore,Northeast,Printer Ink - Color,...,2,27.97,0.00,0.00,55.95,55.95,Direct,False,NaN,137.95
8,DM-006265,2005-01-03,2005,1,Jim Halpert,Prestige Direct,Mid-Market,Scranton,Northeast,Recycled Paper - Letter (Case),...,1,39.27,0.00,0.00,39.27,39.27,Direct,False,NaN,127.10
9,DM-001005,2005-01-03,2005,1,Dwight Schrute,Northeast PA Bank,Enterprise,Scranton,Northeast,Specialty Paper - Glossy (Pack),...,6,35.65,0.15,32.09,213.92,181.83,Email,False,NaN,160.95
10,DM-010020,2005-01-03,2005,1,Michael Scott,Scranton Business Park,SMB,Scranton,Northeast,Color Copy Paper (Pack),...,5,28.87,0.00,0.00,144.33,144.33,Direct,False,NaN,60.62
11,DM-011927,2005-01-03,2005,1,Stanley Hudson,Northeast PA Bank,Enterprise,Scranton,Northeast,DM Executive Binder,...,1,13.60,0.00,0.00,13.60,13.60,Trade Show,False,NaN,23.90
12,DM-006267,2005-01-04,2005,1,Jim Halpert,First National Bank PA,Enterprise,Philadelphia,Mid-Atlantic,Laser Toner - Color,...,4,116.35,0.00,0.00,465.38,465.38,Direct,False,NaN,381.35
13,DM-010010,2005-01-04,2005,1,Michael Scott,Dunmore Correctional,Government,Dunmore,Northeast,DM Executive Binder,...,10,13.97,0.05,6.98,139.67,132.69,Direct,False,NaN,27.16
14,DM-018923,2005-01-04,2005,1,Todd Packer,Albany City Hall,Government,Albany,Northeast,Laser Toner - Color,...,5,126.30,0.00,0.00,631.49,631.49,Email,False,NaN,180.64
15,DM-010012,2005-01-04,2005,1,Michael Scott,Prestige Direct,Mid-Market,Scranton,Northeast,Laser Toner - Color,...,6,121.34,0.00,0.00,728.02,728.02,Email,False,NaN,250.89
16,DM-010018,2005-01-04,2005,1,Michael Scott,Syracuse University,Education,Syracuse,Northeast,Laser Toner - Color,...,4,123.00,0.20,98.40,492.01,393.61,Email,False,NaN,250.89
17,DM-001013,2005-01-04,2005,1,Dwight Schrute,Keystone Manufacturing,Internal,Nashua,Northeast,Recycled Paper - Letter (Case),...,1,41.14,0.05,2.06,41.14,39.08,Phone,False,NaN,183.95
18,DM-011928,2005-01-05,2005,1,Stanley Hudson,Cornell Medical Center,Enterprise,Ithaca,Northeast,Laser Toner - Color,...,2,125.61,0.15,37.68,251.21,213.53,Phone,False,NaN,220.78
19,DM-011923,2005-01-05,2005,1,Stanley Hudson,Horizon Technologies,Internal,Stamford,Northeast,Stapler - Heavy Duty,...,1,19.17,0.00,0.00,19.17,19.17,Phone,False,NaN,34.94

In [21]:
# Checking the number of rows and columns
df.shape

(19405, 21)

In [ ]:
# Checking for null values
df.isnull().sum()

order_id                0
order_date              0
year                    0
month                   0
salesperson             0
client_name             0
client_segment          0
client_city             0
region                  0
product_name            0
product_category        0
quantity                0
unit_price              0
discount_pct            0
discount_amount         0
gross_revenue           0
net_revenue             0
channel                 0
is_returned             0
return_date         18607
monthly_target          0
dtype: int64

In [24]:
# First impression of the dataset
df.describe()

,order_date,year,month,quantity,unit_price,discount_pct,discount_amount,gross_revenue,net_revenue,return_date,monthly_target
count,19405,19405.000000,19405.000000,19405.000000,19405.000000,19405.000000,19405.000000,19405.000000,19405.000000,798,19405.000000
mean,2009-01-27 22:44:36.299922,2008.595053,6.335996,4.966916,34.665653,0.049871,8.677085,172.539555,163.862470,2009-02-03 16:09:01.353383,84.684019
min,2005-01-01 00:00:00,2005.000000,1.000000,1.000000,6.430000,0.000000,0.000000,6.440000,5.300000,2005-02-04 00:00:00,5.750000
25%,2007-01-28 00:00:00,2007.000000,3.000000,2.000000,13.930000,0.000000,0.000000,37.730000,35.910000,2007-01-16 06:00:00,29.700000
50%,2008-12-06 00:00:00,2008.000000,6.000000,3.000000,26.930000,0.050000,0.470000,84.980000,80.550000,2009-01-26 12:00:00,56.540000
75%,2011-02-02 00:00:00,2011.000000,9.000000,6.000000,45.170000,0.100000,7.430000,187.720000,178.120000,2011-02-07 18:00:00,109.950000
max,2013-05-28 00:00:00,2013.000000,12.000000,24.000000,129.570000,0.200000,613.780000,3106.510000,3088.890000,2013-06-20 00:00:00,618.190000
std,NaN,2.366165,3.500606,5.298777,27.976588,0.060830,23.950134,275.136912,262.339295,NaN,83.569879

In [ ]:
# Checking for duplicates
df['order_id'].duplicated().sum()

np.int64(0)

In [ ]:
# Checking column names and what info they contain
df.columns

Index(['order_id', 'order_date', 'year', 'month', 'salesperson', 'client_name',
       'client_segment', 'client_city', 'region', 'product_name',
       'product_category', 'quantity', 'unit_price', 'discount_pct',
       'discount_amount', 'gross_revenue', 'net_revenue', 'channel',
       'is_returned', 'return_date', 'monthly_target'],
      dtype='str')

In [25]:
# Checking the type of the columns
df.dtypes

# Converting date columns to datetime format
date_cols = ['order_date', 'return_date']
for col in date_cols:
    df[col] = pd.to_datetime(df[col])

In [27]:
df['client_name'].nunique()

42